### ISSUE TITLE
Support for em-redis?

### ISSUE THREAD

**Issue by ghost** [soveran/ohm#20]
Hey!

Ohm is awesome! Is there any support for em-redis? Is it planned?

**Comment by brainfunked** [comment]
I managed to get Ohm 1.3.x working with `EM::Synchrony`. Even though we're on 2.x with [redic](https://github.com/amakawa/redic) now, the following information may still be useful.

I replaced the entire `Ohm::Connection` class with an `EM::Synchrony::ConnectionPool` based implementation. However, to get it to work, I had to replace all the instances of `Redis#multi` and `Redis#pipelined` calls to use the yielded connection object instead of the `model.db` object. Calling the `model.db` object inside a `Redis#multi` or `Redis#pipelined` block causes the called fibers in the pool to not be made available again and hence finally, the entire pool hangs:

https://github.com/igrigorik/em-synchrony/blob/master/lib/em-synchrony/connection_pool.rb#L17-L19

The updated code is available here:
https://github.com/brainfunked/ohm/tree/1.3.x

On a side-note, the `Ohm::SoftDelete` plugin in [ohm-contrib](https://github.com/cyx/ohm-contrib) had to be patched with similar [fixes](https://github.com/brainfunked/ohm-contrib/tree/1.2.x).
