### ISSUE TITLE
Finding parent for child objects in list?

### ISSUE THREAD

**Issue by chriso0710** [soveran/ohm#224]
Hi,

I have the following model definition:

```ruby
class Project < Ohm::Model
    attribute :name
    ...
    list :messages, :Message
end

class Message < Ohm::Model
    # only simple attributes, no references
    attribute :mid
    ...
end
```

Message does not reference Project (which was not needed until now). Is there any chance to simply get the parent Project from a Message child object which is in the messages list? 
What would be the best practice to get a reference from a Message object in the list back to the parent Project?

Thanks
Christian

**Comment by soveran** [comment]
Each `Message` will reference just one `Project`, right? If that's the case, I think the best would be to add a reference to each `Message`. With that reference in place, you can even get rid of the list at some point. The first step would be to define the reference in `Message`:

```ruby
class Message < Ohm::Model
  ...

  reference :project, :Project
end
```

With the reference in place, you will have to iterate over each project's messages and populate the references:

```ruby
Project.all.each do |project|
  project.messages.each do |message|
    message.update(project: project)
  end
end
```

At that point you will have both the lists and the references. The next step is to use collections instead of lists, and the final step will be removing the leftover keys that were used for the lists.

In order to use collections instead of lists, rename `list` to `collection` in the definition of `Project`:

```diff
class Project < Ohm::Model
  ...

--- list :messages, :Message
+++ collection :messages, :Message
end
```

While you are in a development or testing environment, check if everything works. If you run into any issue, you can still revert to the lists and you can also contact me so we can troubleshoot. The last step, once you verify everything works, is to remove the leftover keys:

```ruby
Project.all.each do |project|
  project.key[:messages].del
end
```

**Comment by chriso0710** [comment]
Great stuff @soveran. Thank you very much for your detailed answer.

I already guessed that a simple reference might be best practice to point to a Project from Message.
But I do not see reason to further drop the list and use a collection instead. Lists are great for ordered queues and thats the reason I am using them. Any good points (other than syntactic sugar) to migrate to collections?

**Comment by soveran** [comment]
I usually go for lists and sets when a given element belongs to more than one collection, and only if there's no benefit in modeling it with references. Often times you can model the same problem in at least two different ways: for example, imagine sets of users and projects, where a user can be assigned to different projects. Each project could have a set of users, with the downside that given a user you cannot infer in which projects they are in unless you also create a set or projects for each user. The other way to model it would be to create a third model called, for example, subscription.

```ruby
class Subscription < Ohm::Model
  reference :user, :User
  reference :project, :Project
end
```

Your `User` and `Project` models would look like this:

```ruby
class User < Ohm::Model
  collection :subscriptions, :Subscription

  def projects
    subscriptions.map(&:project)
  end
end
```

```ruby
class Project < Ohm::Model
  collection :subscriptions, :Subscription

  def users
    subscriptions.map(&:user)
  end
end
```

The `User#projects` and `Project#users` methods are just a convenience.

In your case, you don't need a third model like `Subscription` because a message belongs to only one project. The only downside I see with having a list instead of a collection is that you have to keep both lists and references consistent. Each time you add or remove a message from a list you also have to update the message's reference to the project. I think there's no other downside.

**Comment by chriso0710** [comment]
Thank you! I think I will stick to my list for now...

**Comment by soveran** [comment]
Perfect! I will close the issue but maybe we can copy this info to the wiki.
