### ISSUE TITLE
Deleted Items Remain in Set

### ISSUE THREAD

**Issue by lynnfaraday** [soveran/ohm#238]
It seems that deleted items stick around in a set, and I wouldn't expect them to.

- Say I have a model X, and another model Y which contains a set of X's.
- I add a few x's to the set, so now it contains [ X1, X2, X3].
- If I delete object X1, it seems to remain in the set in some kind of deleted state.
- Now if I do some operation on Y that affects all its X's, object X1 can come back to life -- but without its data.

Is this the intended behavior?  If so, is there a recommended way to clean this up?  I don't see a good way for Y to be notified when one of its X's has been deleted.

I created a [gist](https://gist.github.com/lynnfaraday/43a0dc300f34fb76cbf9e910a302a616) illustrating this behavior.

**Comment by soveran** [comment]
That's a downside of how it's implemented: sets and lists are intended to be handled manually. In some cases, references and collections can be used instead and they are handled automatically by Ohm. If the use case permits, that's the best option because the underlying representation is still a Set, but when you delete an object it is automatically gone from all the collections that reference it.

Here's an example of that relationship:

```ruby
class Event < Ohm::Model
  attribute :name
  reference :venue, :Venue
end

class Venue < Ohm::Model
  attribute :name
  collection :events, :Event
end
```

But of course that doesn't mean that kind of relationship can solve any problem. A set allows for an object to be present at the same time in various collections, for example let's consider this situation:

```ruby
class Event < Ohm::Model
  attribute :name
  set :participants, :Person
end

class Person < Ohm::Model
  attribute :name
end
```

Those models represent the situation when a person can participate in many events at the same time. Adding a reference to an event in `Person` would be of no use, since that only allows us to model the situation where a person can only be related to one event at any single time.

One idea is to use two sets: a person has a set of events and an event has a set of participants. Then we can use callbacks to add or remove members as needed. You can run this code to see how it behaves:

```ruby
require "ohm"
require "ohm/contrib"

Ohm.redis.call("FLUSHDB")
Ohm.redis.call("SCRIPT", "FLUSH")

class Event < Ohm::Model
  include Ohm::Callbacks

  attribute :name
  set :participants, :Person

  def register(person)
    participants.add(person)
    person.events.add(self)
  end

  def before_delete
    participants.each do |person|
      person.events.delete(self)
    end
  end
end

class Person < Ohm::Model
  include Ohm::Callbacks

  attribute :name
  set :events, :Event

  def before_delete
    events.each do |event|
      event.participants.delete(self)
    end
  end
end

e1 = Event.create(name: "E1")
e2 = Event.create(name: "E2")

p1 = Person.create(name: "P1")
p2 = Person.create(name: "P2")

e1.register(p1)
e1.register(p2)

e2.register(p1)
e2.register(p2)

puts "\ne1.participants"
e1.participants.each do |person|
  p person
end

puts "\ne2.participants"
e2.participants.each do |person|
  p person
end

puts "\np1.events"
p1.events.each do |event|
  p event
end

puts "\np2.events"
p2.events.each do |event|
  p event
end

puts "\ne1 and p2 deleted"

e1.delete
p1.delete

puts "\ne2.participants"
e2.participants.each do |person|
  p person
end

puts "\np2.events"
p2.events.each do |event|
  p event
end
```

**Comment by lynnfaraday** [comment]
That's what I figured.  Thanks.
